config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_items, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    redirect_to articles_path
  end

  def edit; end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def find_items
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="form-group">
  <%= simple_form_for(article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control', :input_html => { 'rows' => 6, 'cols' => 20 } %>
    <%= f.button :submit, class: 'btn btn-outline-success' %>
  <% end %>
</div>

app/views/articles/_navbar.html.erb
<nav class="navbar navbar-light">
  <a class="navbar-brand" href="/articles" >WikiWakaWaka</a>
  <form class="form-inline">
    <a class="btn btn-outline-primary my-2 my-sm-0" href="/articles/new">New Article</a>
  </form>
</nav>

app/views/articles/edit.html.erb
<%= render 'navbar' %>
<h1 class="banner">Update Article</h1>
<div class="form-container">
  <%= render 'form', article: @article  %>
</div>

app/views/articles/index.html.erb
<%= render 'navbar' %>
<div class="container">
<h1 class="banner">Articles</h1>
  <ul>
    <% @articles.each do |art| %>
    <li>
      <div class="article">
      <%= link_to art.title, article_path(art) %>
      <p class="content"><%= art.content %></p>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/articles/new.html.erb
<%= render 'navbar' %>
<h1 class="banner">New Article</h1>
<div class="form-container">
  <%= render 'form', article: @article  %>
</div>

app/views/articles/show.html.erb
<%= render 'navbar' %>
<div class="container-card">
  <div class="card">
<h1 class="banner"><%= @article.title %></h1>
<h3 class="content">"<%= @article.content %>"</h3>
</div>
<div class="buttons">
  <%= link_to edit_article_path, class: "btn btn-outline-success" do %>
    <i class="far fa-edit"></i> Edit
  <% end %>
  <%= link_to article_path, method: :delete, class: "btn btn-outline-danger" do %>
    <i class="far fa-trash-alt"></i> Delete
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>